export const actionTypes = {
  GET_ALL_MOVIES: "GET_ALL_MOVIES",
  SET_ALL_MOVIES: "SET_ALL_MOVIES",
  SET_PAGINATION: "SET_PAGINATION",
  GET_MOVIE_ID: "GET_MOVIE_ID",
  SET_MOVIE_ID: "SET_MOVIE_ID",
};
