export const actionTypes = {
  GET_ALL_MOVIES: "GET_ALL_MOVIES",
  SET_ALL_MOVIES: "SET_ALL_MOVIES",
  SET_PAGINATION: "SET_PAGINATION",
  GET_MOVIE_ID: "GET_MOVIE_ID",
  SET_MOVIE_ID: "SET_MOVIE_ID",
  GET_MOVIE_CREDITS: "GET_MOVIE_CREDITS",
  SET_MOVIE_CREDITS: "SET_MOVIE_CREDITS",
  GET_MOVIE_TRAILER: "GET_MOVIE_TRAILER",
  SET_MOVIE_TRAILER: "SET_MOVIE_TRAILER",
};
